# Generated by Django 5.2.4 on 2025-07-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_number', models.CharField(max_length=255)),
                ('Fuel_date', models.DateField(auto_now_add=True)),
                ('Fuel_Ltr', models.FloatField(max_length=255)),
                ('Fuel_rate_per_ltr', models.FloatField(max_length=255)),
                ('Total_fuel_price', models.FloatField(max_length=255)),
                ('Remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Add_vehicle_numbers', models.CharField(max_length=255)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
